name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*.*"
  pull_request: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Use npm 7.5
        run: |
          npm install -g npm@7.5
      - name: Install dependencies
        run: |
          npm install
        env:
          CI: true
      - name: Linting
        run: npm run test:lint:ci
        env:
          CI: true
