name: Unit Tests

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*.*.*"
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm 8
        run: |
          npm install -g npm@8
      - name: Install dependencies
        run: |
          npm install
        env:
          CI: true

      - name: Transpile for Node.js ${{ matrix.node-version }}
        run: |
          ./node_modules/.bin/lerna exec --bail --concurrency 2 -- ../../node_modules/.bin/swc --config-file ../../swc.config.json index.js --out-file index.js

      - name: Unit tests
        run: npm run test:packages:unit
        env:
          CI: true
